In [1]:
# import libraries
import numpy as np
import pandas as pd
import striplog

In [2]:
df = pd.read_excel('DISC-Sample_mudlog_file.xlsx')

In [3]:
df.head()

,Tot Depth,TVD Depth,ROP ft/hr,WOB,RPM,SPP,TORQUE,FLWpmps,MW IN,MW OUT,...,iC4 main,nC4 main,iC5 main,nC5 main,D Exp,SAND,SHALE,SILTSTONE,CEMENT,DESCRIPTION
0,ft,ft,ft/h,klbs,rpm,psi,klb*f,gpm,ppg,ppg,...,ppm,ppm,ppm,ppm,....,%,%,%,%,NaN
1,7905.0,7905.1,19.0,4.0,122.0,1697.0,3.5,1173.98,8.5,9.2,...,0.0,0.0,0.0,0.0,0.94,-999.25,-999.25,-999.25,100.0,NaN
2,7906.0,7904.1,44.0,8.6,122.0,2380.0,4.02,1333.59,8.5,9.2,...,0.0,0.0,0.0,0.0,0.83,-999.25,-999.25,-999.25,100.0,Cement.
3,7907.0,7914.1,26.8,8.3,81.0,2870.0,2.01,1076.49,9.2,9.2,...,0.0,0.0,0.0,0.0,0.93,-999.25,-999.25,-999.25,100.0,NaN
4,7908.0,7908.2,88.8,8.7,81.0,2862.0,1.81,1076.11,9.2,9.2,...,0.0,0.0,0.0,0.0,0.72,-999.25,-999.25,-999.25,100.0,NaN

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7592 entries, 0 to 7591
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Tot Depth    7592 non-null   object
 1   TVD Depth    7592 non-null   object
 2   ROP ft/hr    7592 non-null   object
 3   WOB          7592 non-null   object
 4   RPM          7592 non-null   object
 5   SPP          7592 non-null   object
 6   TORQUE       7592 non-null   object
 7   FLWpmps      7592 non-null   object
 8   MW IN        7592 non-null   object
 9   MW OUT       7592 non-null   object
 10  TMP IN       7592 non-null   object
 11  TMP OUT      7592 non-null   object
 12  T GAS main   7592 non-null   object
 13  C1  main     7592 non-null   object
 14  C2  main     7592 non-null   object
 15  C3  main     7592 non-null   object
 16  iC4 main     7592 non-null   object
 17  nC4 main     7592 non-null   object
 18  iC5 main     7592 non-null   object
 19  nC5 main     7592 non-null   object
 20  D Exp        7592 non-null   object
 21  SAND         7592 non-null   object
 22  SHALE        7592 non-null   object
 23  SILTSTONE    7592 non-null   object
 24  CEMENT       7592 non-null   object
 25  DESCRIPTION  782 non-null    object
dtypes: object(26)
memory usage: 1.5+ MB

Fisrtly, we want to select all rows where shale is equal or greater than 70

In [104]:
# we convert to float because we cannot use comparison operators between strings
# we also start from the second index because '%' cannot be converted into a float
df['SHALE'] = pd.to_numeric(df['SHALE'][1:])
df['SHALE']

0          NaN
1      -999.25
2      -999.25
3      -999.25
4      -999.25
         ...
7587   -999.25
7588   -999.25
7589   -999.25
7590   -999.25
7591     70.00
Name: SHALE, Length: 7592, dtype: float64

In [105]:
df1 = df[df['SHALE'] >= 70] 
df1

,Tot Depth,TVD Depth,ROP ft/hr,WOB,RPM,SPP,TORQUE,FLWpmps,MW IN,MW OUT,...,iC4 main,nC4 main,iC5 main,nC5 main,D Exp,SAND,SHALE,SILTSTONE,CEMENT,DESCRIPTION
86,7990.0,7990.0,58.5,12.9,80.0,2872.0,4.24,1065.35,9.2,9.2,...,6.0,0.0,1.0,1.0,0.86,-999.25,80.0,-999.25,20.0,Cement.
87,7991.0,7991.0,94.0,12.7,81.0,2875.0,5.3,1063.39,9.2,9.2,...,6.0,0.0,0.0,1.0,0.77,-999.25,80.0,-999.25,20.0,NaN
88,7992.0,7992.0,109.5,12.2,81.0,2874.0,4.58,1058.3,9.2,9.2,...,6.0,0.0,0.0,0.0,0.62,-999.25,80.0,-999.25,20.0,"Shale: grn, lt gry, sft - frm, stk,"
89,7993.0,7993.0,6.3,10.4,79.0,2877.0,3.57,1059.57,9.2,9.2,...,5.0,2.0,7.0,10.0,1.24,-999.25,80.0,-999.25,20.0,"subblky, blky, subfiss-fiss, non calc."
90,7994.0,7994.0,25.9,7.6,81.0,2839.0,3.12,1052.27,9.2,9.2,...,7.0,1.0,4.0,10.0,0.92,-999.25,80.0,-999.25,20.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7548,15343.0,15285.3,15.1,11.7,111.0,3922.0,11.18,877.15,11.2,10.6,...,21.0,6.0,3.0,2.0,1.01,30.0,70.0,-999.25,-999.25,NaN
7555,15350.0,15292.1,15.4,23.6,111.0,3915.0,14.55,877.25,11.2,10.6,...,17.0,8.0,4.0,5.0,1.2,30.0,70.0,-999.25,-999.25,NaN
7556,15351.0,15293.2,34.5,24.6,111.0,3915.0,13.55,877.37,11.2,10.6,...,17.0,8.0,3.0,5.0,1.05,30.0,70.0,-999.25,-999.25,NaN
7560,15355.0,15297.1,25.3,23.2,111.0,3911.0,14.32,877.01,11.2,10.6,...,17.0,6.0,4.0,4.0,1.1,30.0,70.0,-999.25,-999.25,NaN
7591,15385.0,15326.9,13.6,20.6,111.0,3934.0,12.42,877.08,11.2,10.6,...,24.0,8.0,5.0,3.0,1.18,30.0,70.0,-999.25,-999.25,NaN

In [81]:
df1.to_csv('Shale_great_70.csv', index = False)

Next we select all rows with shale equal to 100

In [82]:
df2 = df[df['SHALE'] == 100]
df2

,Tot Depth,TVD Depth,ROP ft/hr,WOB,RPM,SPP,TORQUE,FLWpmps,MW IN,MW OUT,...,iC4 main,nC4 main,iC5 main,nC5 main,D Exp,SAND,SHALE,SILTSTONE,CEMENT,DESCRIPTION
146,8049.0,8049.0,68.2,7.4,82.0,2938.0,3.33,1077.43,9.2,9.3,...,11.0,0.0,0.0,0.0,0.75,-999.25,100.0,-999.25,-999.25,NaN
147,8050.0,8050.0,70.7,8.3,82.0,2943.0,3.73,1075.38,9.2,9.3,...,11.0,0.0,0.0,0.0,0.76,-999.25,100.0,-999.25,-999.25,NaN
148,8051.0,8051.0,119.0,8.9,82.0,2940.0,3.72,1076.61,9.2,9.3,...,9.0,0.0,0.0,0.0,0.67,-999.25,100.0,-999.25,-999.25,"Shale: lt grn- gry, occ sft, frm - mod hrd, s..."
177,8080.0,8080.0,127.7,10.0,82.0,2970.0,4.31,1076.82,9.2,9.3,...,17.0,3.0,0.0,0.0,0.67,-999.25,100.0,-999.25,-999.25,NaN
178,8081.0,8081.0,48.2,9.9,82.0,2968.0,4.19,1075.62,9.2,9.3,...,4.0,0.0,0.0,0.0,0.85,-999.25,100.0,-999.25,-999.25,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7052,14857.0,14806.7,51.1,4.5,80.0,1224.0,12.35,187.17,10.6,10.6,...,0.0,0.0,0.0,0.0,0.66,-999.25,100.0,-999.25,-999.25,NaN
7053,14858.0,14808.1,116.5,5.6,80.0,1227.0,13.13,187.17,10.6,10.6,...,0.0,0.0,0.0,0.0,0.56,-999.25,100.0,-999.25,-999.25,NaN
7083,14887.0,14836.1,35.5,4.7,80.0,1283.0,11.57,187.17,10.6,10.6,...,0.0,0.0,0.0,0.0,0.72,-999.25,100.0,-999.25,-999.25,FROM 14827'-14902'
7084,14888.0,14837.0,38.9,4.1,80.0,1283.0,11.24,187.17,10.6,10.6,...,0.0,0.0,0.0,0.0,0.69,-999.25,100.0,-999.25,-999.25,"Shale: Gy - dk gy , hrd, blky, occ v sdy, non ..."
7085,14889.0,14837.9,38.9,5.5,80.0,1283.0,12.04,187.17,10.6,10.6,...,0.0,0.0,0.0,0.0,0.73,-999.25,100.0,-999.25,-999.25,NaN

In [83]:
df2.to_csv('Shale_equals_100.csv', index = False)

Now we want to select all rows where the description is Cement

In [111]:
df['DESCRIPTION'] = df['DESCRIPTION'].astype(str)

In [112]:
def Cement_string(description):
    if 'Cement' in description:
        return True
    else:
        return False

In [113]:
df3 = df[df['DESCRIPTION'].apply(lambda x:Cement_string(x))]
df3

,Tot Depth,TVD Depth,ROP ft/hr,WOB,RPM,SPP,TORQUE,FLWpmps,MW IN,MW OUT,...,iC4 main,nC4 main,iC5 main,nC5 main,D Exp,SAND,SHALE,SILTSTONE,CEMENT,DESCRIPTION
2,7906.0,7904.1,44.0,8.6,122.0,2380.0,4.02,1333.59,8.5,9.2,...,0.0,0.0,0.0,0.0,0.83,-999.25,-999.25,-999.25,100.0,Cement.
30,7934.0,7934.2,12.5,9.6,81.0,2865.0,2.81,1059.98,9.2,9.2,...,4.0,0.0,1.0,1.0,1.1,-999.25,40.00,-999.25,60.0,Cement.
56,7960.0,7960.0,199.1,12.9,81.0,2872.0,4.95,1062.68,9.2,9.2,...,5.0,0.0,0.0,0.0,0.62,-999.25,60.00,-999.25,40.0,Cement.
86,7990.0,7990.0,58.5,12.9,80.0,2872.0,4.24,1065.35,9.2,9.2,...,6.0,0.0,1.0,1.0,0.86,-999.25,80.00,-999.25,20.0,Cement.

In [88]:
df3.to_csv('Cement_decriptions.csv', index = False)

Now we want to expand the description of all rows with Shale greater than 70

In [119]:
df1['DESCRIPTION'] =df1['DESCRIPTION'].astype(str)

C:\Users\peter\AppData\Local\Temp\ipykernel_23788\3555106058.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['DESCRIPTION'] =df1['DESCRIPTION'].astype(str)

In [120]:
from striplog import Lexicon

In [121]:
Lexicon.default()

{'lithology': ['overburden', 'sandstone', 'siltstone', 'shale', 'conglomerate', 'mudstone', 'limestone', 'dolomite', 'salt', 'halite', 'anhydrite', 'gypsum', 'sylvite', 'clay', 'mud', 'silt', 'sand', 'gravel', 'boulders'], 'modifier': ['silty', 'sandy', 'shale?y', 'muddy', 'pebbly', 'gravell?y'], 'amount': ['streaks?', 'veins?', 'stringers?', 'interbed(?:s|ded)?', 'blotch(?:es)?', 'bands?', 'fragments?', 'impurit(?:y|ies)', 'abundant', 'minor', 'some', 'rare', 'flakes?', 'trace', '[-.\\d]+%', '[-.\\d]+pc', '[-.\\d]+per ?cent'], 'grainsize': ['vf(?:-)?', 'f(?:-)?', 'm(?:-)?', 'c(?:-)?', 'vc', 'very fine(?: to)?', 'fine(?: to)?', 'medium(?: to)?', 'coarse(?: to)?', 'very coarse', 'v fine(?: to)?', 'med(?: to)?', 'med.(?: to)?', 'v coarse', 'grains?', 'granules?', 'pebbles?', 'cobbles?', 'boulders?'], 'colour': ['red(?:dish)?', 'gray(?:ish)?', 'grey(?:ish)?', 'black(?:ish)?', 'whit(?:e|ish)', 'blu(?:e|ish)', 'purpl(?:e|ish)', 'yellow(?:ish)?', 'green(?:ish)?', 'brown(?:ish)?', 'light', 'dark', 'sandy'], 'synonyms': {'Overburden': ['Drift'], 'Anhydrite': ['Gypsum'], 'Salt': ['Halite', 'Sylvite']}, 'splitters': [' with ', ' contain(?:s|ing) ', '\\. '], 'parts_of_speech': {'noun': ['lithology'], 'adjective': ['colour', 'grainsize', 'modifier'], 'subordinate': ['amount']}, 'abbreviations': {'gt': 'gritty', 'dist': 'distillate', 'gr': 'grained', 'LSD': 'legal subdivision', 'ptg': 'parting', 'alg': 'algal', 'mnr': 'minor', 'Assem': 'Assem', 'Vad': 'vadose', 'MCW': 'mud cut water', 'Pch': 'patch', 'gd': 'good', '/': 'with', 'ga': 'gauged', 'bulb': 'bulbous', 'Var': 'variation', 'gn': 'green', 'alt': 'altering', 'Gil': 'gilsonite', 'Oyst': 'oyster', 'sch': 'schist', 'Clst': 'claystone', 'ves': 'vesicular', 'Nod': 'nodules', 'tt': 'tightly', 'V.P.S.': 'very poor sample V.P.S.', 'asph': 'asphaltic', 'SIP': 'shut in pressure', 'tn': 'tan', 'G&OCM': 'gas and oil cut mud', 'DI': 'dual induction log', 'Mol': 'mollusca', 'Inoc': 'inoceramus*', 'spec': 'speckled', '@': 'at', 'Amph': 'amphipora*', 'vert': 'vertical', 'lrg': 'larger', 'md': 'muddy', 'wthrd': 'weathered', 'Brec': 'breccia', 'D & A': 'dry and abandoned', 'fau': 'fauna', 'depau': 'depauperate', 'shad': 'shadow', 'DF': 'derrick floor', 'gy': 'gray', 'Elev': 'elevation', 'indst': 'indistinct', 'Syring': 'syringopora*', 'fac': 'faceted', 'GL': 'guard log', 'brhg': 'branching', 'Gt': 'grit', 'Gr': 'grains', 'FIt': 'fault', 'Tas': 'tasmanites*', 'Spr': 'spore', 'fenst': 'fenestral', 'plag': 'plagioclase', 'p': 'poorly', 'Spk': 'speck', 'Spl': 'sampole', 'SNP': 'sidewall neutron porosity log', 'n.s.': 'no sample', 'Clcar': 'calcarenite', 'pbl': 'pebble (4-64 mm)', 'cmt': 'cemented', 'Spg': 'sponge', 'Grv': 'gravel', 'Cyp': 'cypridopsis*', 'Grt': 'granite', 'SP': 'spontaneous potential', 'Res': 'residue', 'Bioh': 'bioherm', 'Biost': 'biostrom', 'tex': 'texture', 'Brach': 'brachiopod', 'hydc': 'hydrocarbon', 'Ren': 'renalcis*', 'Biot': 'biotite', 'Peld': 'pelletoid', 'Bld': 'boulder', 'ter': 'terriginous', 'splty': 'splintery', 'acic': 'acicular', 'sug': 'sugary', 'bdd': 'bedded', 'bdg': 'bedding', 'gl': 'glassy', 'abd': 'abundant', 'Intst': 'intersticies', 'Micr': 'micrite', 'O str': 'Ostracod', 'Clcsp': 'calcisphere', 'bl': 'bluish', 'abs': 'absent', 'abt': 'about', 'conspic': 'conspicuous', 'Spfool': 'superficial olite', 'sli': 'slightly', 'med': 'medium', 'O&SW': 'oil and salt water', 'biocl': 'bioclastic', 'Agg': 'aggregate', 'DST': 'drill stem test', 'Mn': 'manganese', 'psdo': 'pseudo', 'len': 'lentilcular', 'rug': 'rugosa', 'Wd': 'wood', 'hkl': 'hackly', 'DLL': 'dual laterolog', 't.s.': 'thin section', 'Mtrx': 'matrix', 'crpxln': 'crystocrystalline', 'Zn': 'zone', 'Anthr': 'anthracite', 'altg': 'alternating', 'blksh': 'blackish', 'bor': 'boreding', 'dru': 'drusy', 'ctd': 'coated', 'Conc': 'concretion', 'wtr cush': 'water cushion', 'ctc': 'contact', 'micropor': 'microporosity', 'Zr': 'zircon', 'Cono': 'conodont', 'sft': 'soft', 'Piso': 'pisoid', 'LL': 'laterolog', 'lmn': 'limonitic', 'volc': 'volcanics', 'Ctgs': 'cuttings', 'apr': 'apparent', 'tr': 'trace', 'app': 'appear', 'brt': 'bright', 'ls': 'limestone', 'Slt': 'silt', 'Circ': 'circulate', 'aph': 'aphanitic', 'oomol': 'oomoldic', 'brk': 'brackish', 'vit': 'vitreous', 'org': 'organic', 'n.v.p.': 'no visible porosity', 'w/': 'with', 'brd': 'bored', 'intxln': 'intercrystalline', 'Para': 'paraparchites*', 'Fp': 'flowing pressure', 'Ft': 'foot', 'perf': 'perforated', '&': 'and', 'fen': 'fenestraal', 'pred': 'predominantly', 'Phlog': 'phloaopite', 'perm': 'permeability', 'fibr': 'fibrous', 'msm': 'metasomatic', 'cht': 'chert', 'Fe': 'iron-ferruginous', 'dns': 'denser', 'vi': 'violet', 'fros': 'frosted', 'calc': 'calcitareous', 'Fm': 'formation', 'pres': 'preservation', 'cntrt': 'contorted', 'wvy': 'wavy', 'vps': 'very poor samples', 'ooc': 'oocastic', 'musc': 'muscovite', 'glas': 'glassy', 'Sh': 'shale', 'lchd': 'leached', 'rhb': 'rhombic', 'glau': 'glauconitic', 'Brac': 'brachiopod', 'choc': 'chocolate', 'chit': 'chitinous', 'Str': 'structure', 'Sl': 'slate', 'clus': 'cluster', 'Sa': 'salt', 'Cmt': 'cement', 'lmpy': 'lumpy', 'Sd': 'sand', 'intrapar': 'intraparticle', 'phos': 'phosphatic', 'prly': 'pearly', 'Lstr': 'lustre', 'tns': 'tension', 'f': 'finely', 'fls': 'flesh', 'des': 'descript', 'SW': 'salt water', 'flt': 'faulted', 'Cbl': 'cobble', 'plty': 'platy', 'lithgr': 'lithographic', 'flk': 'flake', 'W.R.': 'washed residue', 'SO': 'show of oil', 'v': 'very', 'deb': 'debris', 'slty': 'silty', 'fld': 'feldsparthic', 'flg': 'flaggy', 'ptch': 'patches', 'Lig': 'lignite', 'mica': 'micaeous', 'bent': 'bentonitic', 'Min': 'mineral', 'sy-Ca': 'sparry calcite', 'Lim': 'limonite', 'Invtb': 'invertebrate', 'sps': 'sparsly', 'Mid': 'middle', 'yelsh': 'ish', 'sph': 'spherules', 'spl': 'sample', 'Ls': 'limestone', 'tab': 'tabular', 'Plcy': 'palecypod', 'scat': 'scattered', 'psool': 'pseudo oolitic', 'GR': 'gamma ray', 'spsly': 'sparsly', 'Bdeye': 'birdseye', 'purp': 'purple', 'Pyr': 'pyrite', 'hom': 'homogeneous', 'Kao': 'kaolin', 'Spic': 'spicule', 'hor': 'horizontal', 'Belm': 'belemnites*', 'sid': 'sideritic', 'aft': 'after', 'Rhb': 'rhomb', 'Typ': 'type', 'sim': 'similar', 'sil': 'siliceous', 'frag': 'fragmental', 'lam': 'laminated', 'fr': 'fair', 'mar': 'maroon', 'frac': 'fractured', 'srt': 'sorting', 'Dol': 'dolomite', 'I.P.': 'in part', 'cpct': 'compact', 'max': 'maximum', 'insl': 'insoluble', 'lac': 'lacustrine', 'Mrl': 'marl', 'mag': 'magnetic', 'Ctc': 'contact', 'ireg': 'irregular', 'lav': 'lavender', 'IAB': 'initial air blow', 'fl': 'filled', 'Tril': 'trilobite', 'Foram': 'foraminifera', 'MMCFG': 'million cubic feet of gas', 'Clvg': 'cleavage', 'Alg': 'algal', 'sp': 'spotty', 'Deer': 'decrease', 'Microspr': 'microspar', 'su': 'sulphurous', 'or': 'orangish', 'strk': 'streaked', 'stri': 'striated', 'sh': 'shale', 'Moll': 'mollusc', 'spkld': 'speckled', 'sm': 'smooth', 'sl': 'slightly', 'sc': 'scales', 'sb': 'sub', 'sa': 'salt', 'strg': 'stringer', 'Trip': 'tripoli', 'Equiv': 'equivalent', 'lse': 'loose', 'mnut': 'minute', 'BHCS': 'bore hole compensated sonic', 'Cal': 'caliper', 'Chk': 'chalk', 'Biomi': 'biomicrite', 'brit': 'brittle', 'coln': 'colonial', 'Smwt': 'somewhat', 'Rf': 'reef', 'Cht': 'chert', '(D)': 'development', 'decr': 'decreasing', 'Rk': 'rock', 'RT': 'rotary table', 'fis': 'fissile', 'cln': 'clean', 'xl': 'crystalline', 'cbl': 'cobble (64-256 mm)', 'Aglm': 'agglomerate', 'Evap': 'evapourite', 'sa-c': 'salt castic', 'fib': 'fibrous', 'imp': 'impression', 'lt': 'lighter', 'eux': 'euxinic', 'cren': 'crenulated', 'gty': 'gravity', 'dess': 'dessiccation', 'clr': 'clear', 'TSTM': 'too small to measure', 'Bas': 'basalt', 'Shw': 'show', 'nod': 'nodule', 'uncons': 'unconsolidated', 'rexl': 'recrystallization', 'Cav': 'cavernous', 'FAB': 'fair air blow', 'aprox': 'approximately', 'â‚µ': 'core', 'Schm': 'schist', 'Shl': 'shell', 'xln': 'crystalline', 'Rad': 'radial', 'Oomol': 'oomold', 'Dist': 'distillate', 'extr': 'extremely', 'l': 'lower', 'Anhy': 'anhydrite', 'intv': 'interval', 'Stach': 'stachyodes*', 'crpxl': 'cryptocrystalline', 'Poln': 'pollen', 'Chtz': 'chitinozoa', 'MCFG': 'thousand cubic feet of gas', 'frmwk': 'framework', 'Lith': 'lithology', 'Macrofos': 'macrofossil', 'prphy': 'porphyry', 'Lut': 'lutite', 'OFM': 'oil flecked mud', 'Asph': 'assemblage', 'intpar': 'interparticle', 'Perm': 'permeability', 'Bdst': 'boundstone', 'chty': 'cherty', 'meta': 'metamorphic', 'ex': 'excellent', 'hrtl': 'horizontal', 'p-p': 'pin point', 'zeo': 'zeolite', 'n/s': 'no show', 'nac': 'nacerous', 'Wtr': 'water', 'apprx': 'approximate', 'rr': 'rare', 'Musc': 'muscovite', 'intclas': 'intraclastic', 'rep': 'replacedment', 'porcel': 'porcelaneous', 'BOPH': 'barrels of oil per hour', 'rd': 'rounded', 'rf': 'reefoid', 'sml': 'small', 'blk': 'black', 'IP': 'initial production', 'bld': 'bladed', 'Tub': 'tube', 'Pisol': 'pisolite', 'mtx': 'matrix', 'lmy': 'limy', 'Phos': 'phosphate', 'crd': 'cored', 'G': 'gas', 'Spo': 'spore', 'GCM': 'gas cut mud', 'SGCM': 'slight gas cut mud', 'OWWO': 'old well worked over', 'Novac': 'novaculite', 'rhmb': 'rhombic', 'argl': 'argillate', 'W': 'west', 'carb': 'carbonaceous', 'Frac': 'fracture', 'freq': 'frequent', 'ES': 'electric', 'Pyrxn': 'pyroxene', 'g': 'good', 'Contam': 'contamination', 'srtg': 'Sorteding', 'Chal': 'chalcedony', 'fspr': 'feldsparathic', 'Char': 'charophyte', 'SSO': 'slight show of oil', 'Hyde': 'hydrocarbon', 'w': 'well', 'intgn': 'inter grown', 'vrtb': 'vertebrate', 'Sphal': 'sphalerite', 'intpt': 'interpretation', 'cche': 'caliche', 'Frg': 'fringe', 'sacc': 'saccharoidal', 'onc': 'oncolites', 'Slick slick': 'slickenside', 'Diagn': 'diagenesis', 'zn': 'zone', 'Imp': 'impression', 'sblit': 'sublithic', 'Prod': 'production', 'Incl': 'inclusion', 'Frag': 'fragment', 'sphal': 'sphalerite', 'Iran': 'granule', 'dtrl': 'detritalus', 'wthd': 'weathered', 'WCM': 'water cut mud', 'GCW': 'gas cut water', 'Pet': 'petroleum', 'Microstyl': 'microstylolite', 'Volc': 'volcanic', 'BWPH': 'barrels of water per hour', 'thru': 'throughout', 'intcl': 'intraclasts', 'Biosp': 'biosparite', 'Girv': 'girvanella*', 'OWDD': 'oil well drilled deeper', 'consol': 'consolidated', 'Fus': 'fusulinid', 'sz': 'size', 'grysh': 'greyish', 'mrlst': 'marlstone', 'Strk': 'streak', 'SGCW': 'slight gas cut water', 'crnk': 'crinkled', 'Rbl': 'rubble', 'Fuc': 'fucoid', 'bdeye': 'birdseye', 'gyp': 'gypsumiferous', 'orng': 'orange', 'Endo': 'endothyra*', 'BHFP': 'bottom hole flow pressure', 'Xl': 'crystal', 'stn': 'staining', 'Qtz': 'quartz', 'csg': 'casing', 'Chlor': 'chlorite', 'r': 'rare', 'mky': 'milky', 'str': 'streak', 'Onc': 'oncolite', 'Btm': 'bottom', 'Slst': 'siltstone', 'dissem': 'disseminated', 'spr': 'sparry', 'Pap': 'paper', 'grnt': 'granite', 'Par': 'particle', 'ang': 'angular', 'Descr': 'description', 'intgwn': 'intergrown', 'Stylio': 'styliolina*', 'Intclas': 'intraclast', 'Rem': 'remains', 'chlor': 'chlorite', 'euhd': 'euhedral', 'Pend': 'pendularous', 'Rec': 'recovery', 'grnl': 'granule (2-4 mm)', 'Calc': 'calcite', 'p.d': 'pressure deformation', 'recem': 'recemented', 'strgr': 'stringer', 'lig': 'lignitic', 'Glauc': 'glauconite', 'intbd': 'interbedded', 'lim': 'itic', 'mic': 'micro', 'Db': 'diabase', 'Port por': 'porosity', 'Ech': 'echinoid', 'lit': 'lithic', 'Fluor': 'fluoresceince', 'vrvd': 'varved', 'Arag': 'aragonite', 'vgt': 'varigated', 'Clus': 'cluster', 'mot': 'mottled', 'surf': 'surface', 'pos': 'possibility', 'plas': 'plastic', 'pyr': 'pyritized', 'In': 'inch', 'kao': 'kaolin', 'Orbit': 'Orbitolina', 'MLL': 'microlaterolog', 'sdy': 'sandy', 'Mic': 'micaceous', 'Plt': 'plant', 'assoc': 'associated', 'rthy': 'earthy', 'Ivan': 'ivanovia*', 'suc': 'sucrosic', 'intercal': 'intercalated', 'glos': 'glossy', 'typ': 'typical', 'abv': 'above', 'MCO': 'mud cut oil', 'Unconf': 'unconformity', 'Bent': 'bentonite', 'dol': 'dolomitic', 'dom': 'dominant', 'flor': 'fluorescence', 'sltst': 'siltstone', 'brec': 'brecciated', 'Stri': 'striae', 'dism': 'disseminated', 'BHT': 'bottom hole temperature', 'exv': 'extrusive', 'Pol': 'polish', 'GTS': 'gas to surface', 'Mbr': 'member', 'exp': 'exposed', 'Pybit': 'pyrobitumen', 'a.a.': 'same as above sample', 'intlam': 'interlaminated', 'sd': 'sand (1/16-2 mm)', 'Rpl': 'ripple', 'dend': 'dendritic', 'pkr': 'packer', 'drlg': 'drilling', 'Spher': 'spherule', 'Hal': 'halitiferous', 'lstr': 'lustre', 'Exclas': 'extraclast', 'ML': 'microlog, minilog', 'anhy': 'anhydritic', 'drlr': 'driller', 'Rud': 'rudist', 'grapst': 'grapestone', 'Bubl': 'bubble', 'pris': 'prismatic', 'Bnd': 'band', 'och': 'ochre', 'spher': 'spherulitic', 'Jt': 'joint', 'occ': 'occasional', 'Wl': 'well', 'varic': 'varicolored', 'intrlam': 'interlaminated', 'O&G': 'oil and gas', 'mnrl': 'mineralized', 'Shlt por': 'shelter porosity', 'AOF': 'absolute open flow', 'Gyp': 'gypsumiferous', 'Bit': 'bitumen', 'Gast': 'gastropod', 'Pst': 'pumice-stone', 'PB': 'plugged back', 'Stromlt': 'stromatolite', 'BO': 'barrels of oil', 'dk': 'darker', 'CN': 'compensated neutron', 'KB': 'kelly bushing', 'dd': 'dead', 'Intvl': 'interval', 'stromlt': 'stromatolite', 'Fspr': 'feldspar', 'Milid': 'miliolid', 'cotg': 'coateding', 'cotd': 'coateding', 'repl': 'replacement', 'slily': 'slightly', 'struc': 'structure', 'SO&G': 'show of oil and gas', 'gen': 'generally', 'hetr': 'heterogeneous', 'crs': 'coarse', 'bar': 'baritic', 'bas': 'basaltic', '(W)': 'wildcat', 'shy': 'shaly', 'FDL': 'formation density log', 'w/o': 'without w/o', 'BW': 'barrels of water', 'rsns': 'resinous', 'PL': 'proximity log', 'gran': 'granular', 'BWPD': 'barrels of water per day', 'x': 'cross', 'grad': 'grading', 'Qtzt': 'quartzite', 'crm': 'cream', 'res': 'residuual', 'Pt': 'part', 'OTD': 'old total depth', 'contam': 'contaminated', 'S.W.C.': 'sidewall core', 'qtz': 'quartz', 'magnt': 'magnetite', 'Pel': 'pellet', 'num': 'numerous', 'sec': 'secondary', 'fnly': 'finly', 'arg': 'argillaceous', 'ark': 'arkosic', 'rmn': 'remainant', 'prim': 'primary', 'volat': 'volatile', 'SOCW': 'slight oil cut water', 'piso': 'pisolitic', 'pkish': 'pinkish', 'metaph': 'metamorphosed', 'trnsp': 'transparent', 'irr': 'irregular', 'hornbd': 'hornblend', "'' or do": 'ditto', 'biost': 'biostromal', 'gept': 'geopetal', 'trnsl': 'translucent', 'PD': 'per day', 'PH': 'per hour', 'SO&W': 'show of oil and water', 'Vnlet': 'veinlet', 'Tham': 'thamnopora*', 'wg': 'vuggy', 'C': 'coal', 'men': 'meniscus', 'exclas': 'extraclastic', 'lg': 'long', 'jt': 'jointing', 'comp': 'completion', 'gnsh': 'greenish', 'wk': 'weak', 'wi': 'with', 'wh': 'white', 'Exv': 'extrusive rock', 'S': 'sonic, acoustilog', 'magn': 'magnetic', 'gywk': 'graywacke', 'G.W.': 'granite wash', 'Satm sat': 'saturation', 'tub': 'tubular', 'tuf': 'tuffaceous', 'coq': 'coquina', 'vug': 'vugular', 'c': 'coarsely', 'fnt': 'faintly', 'dkr': 'darker', 'cov': 'covered', 'conch': 'conchoidal', 'intgran': 'intergranular', 'SI': 'shut in', 'Chit': 'chitinous', 's': 'small', 'Meta': 'metamorphic rock', 'Sst': 'sandstone', 'brak': 'brackish', 'uni': 'uniform', 'com': 'common', 'cotd gn': 'coated grains', 'Het': 'Heterostegina', 'foram': 'foraminiferal', 'chky': 'chalky', 'cl': 'clastic', 'cb': 'carbonized', 'Glas': 'glass', 'rad': 'radiating', 'poly': 'polygonal', 'hvy': 'heavy', 'pol': 'polished', 'Pent': 'pentamerus*', 'Hem': 'hematite', 'tgh': 'tough', 'cp': 'compare', 'Surf': 'surface', 'ps': 'pseudo-', 'frg': 'fringing', 'pt': 'partly', 'Bur': 'burrow', 'fri': 'friable', 'blsh': 'bluish', 'pch': 'patchy', 'stmg': 'streaming', 'frs': 'fresh', 'skel': 'skeletal', 'pyrbit': 'pyrobitumen', 'pk': 'pink', 'devit': 'devitrified', 'authg': 'authigenic', 'pl': 'plant', 'cly': 'clayey', 't.b.': 'thin-bedded', 'Tr': 'trace', 'IES': 'induction electric', 'WAB': 'weak air blow', 'lge': 'large', 'spic': 'spicular', 'psi': 'pounds per square inch', 'crbnt': 'carbonate', 'Tp': 'top', 'Pkst': 'packstone', 'Sedm': 'sediment', 'Cont': 'content', 'xbdg': 'cross-bedding', 'gns': 'gneiss', 'micgr': 'micrograined', 'Cl': 'clay', 'slt': 'silt', 'vcol': 'varicolored', 'undly': 'underlying', 'grnt.w': 'granite wash', 'n': 'no, none, non', 'contm': 'contaminated', 'sln': 'solution', 'rbl': 'rubblbly', 'fuc': 'fucoidal', 'Intr': 'intrusive', 'cvg': 'cavings', 'k': 'permeabilityable', 'slb': 'slabby', 'FTAB': 'faint air blow', 'DIL': 'dual induction laterolog', 'pyrcl': 'pyroclastic', 'cons': 'considerable', 'rndd': 'rounded', 'bot': 'botryoidal', 'Sel': 'selenite', 'vn': 'vein', 'Tf': 'tuffaceous', 'styl': 'stylotitic', 'conc': 'concretionary', 'mott': 'mottled', 'xlam': 'cross-laminated', 'x-strat': 'cross-stratified', 'Strom': 'stromatoporoid', 'ig': 'igneous', 'pap': 'papery', 'incr': 'increasing', 'litt': 'littoral', 'intstl': 'interstitial', 'bioturb': 'bioturbated', 'PPM': 'parts per million', 'GAP': 'good air blow', 'Repl': 'replaced', 'lith': 'lithographic', 'elong': 'elongate', 'Chara': 'charophytes', 'sat': 'saturated', 'incl': 'inclusion', 'Coq': 'coquina', 'Vug': 'vug', 'Cor': 'coral', 'intst': 'intersticitial', 'cncn': 'concentric', 'rng': 'range', 'orth': 'orthoclase', 'rdsh': 'redish', 'syn': 'syntaxial', 'Microfos': 'microfossilferous', 'phr': 'phreatic', 'Wkst': 'wackestone', 'pisol': 'pisolitic', 'Col': 'color', 'Jasp': 'jasper', 'Mat': 'material', 'Mbl': 'marble', 'intxl': 'intercrystalline', 'detr': 'detrital', 'sed': 'sedimentary', 'x-bd': 'cross-bedded', 'gsy': 'grasy', 'OWPB': 'oil well plugged back', 'min': 'mineralized', 'Sol': 'Soution', 'Vn': 'vein', 'col': 'colored', 'x-lam': 'cross-laminated', 'thn': 'thin', 'thk': 'thick', 'fltg': 'floating', 'Ig': 'igneous rock', 'imbd': 'imbedded', 'ck': 'choke', 'BHP': 'bottom hole pressure', 'yel': 'yellow', 'Orth': 'orthoclase', 'sptd': 'spottedy', 'spty': 'spottedy', 'Sphaer': 'sphaerocodium*', 'Pbl': 'pebble', 'intfrag': 'interfragmental', 'Scaph': 'scaphopod', 'resd': 'residual', 'Bd': 'bed', 'Fe-mag': 'ferro-magnesian', 'sks': 'slickensided', 'rexlzd': 'recrystallized', 'Bm': 'basement', 'Glob': 'globigerina*', 'elg': 'elongate', 'unident': 'unidentifiable', 'Fau': 'fauna', 'Gal': 'galeolaria*', 'cub': 'cubic', 'Fac': 'facet', 'Glos': 'gloss', 'Gab': 'gabbro', 'bnd': 'banded', 'Oo': 'ooid', 'Gns': 'gneiss', 'amb': 'amber', 'strat': 'strataified', 'amm': 'ammonite', 'vis': 'visible', 'mos': 'mosaic', 'por': 'poroussity', 'uncons.': 'unconsolidated', 'embd': 'embedded', 'Dia': 'diameter', 'rnd': 'rounded', 'sbang': 'subangular', 'cntr': 'centered', 'mol': 'moldic', 'Cvg': 'caving', 'bit': 'bitumeninous', 'Micropor': 'micropore', 'S.W.': 'salt water', 'amt': 'amount', 'mod': 'moderate', 'Crin': 'crinoidal', 'Lyr': 'layer', 'brn': 'brown', 'boudg': 'boudinage', 'OC': 'oil cut', 'Microol': 'micro-oolite', 'Ltl': 'little', 'V.op': 'valve open', 'amor': 'amorphous', 'Ark': 'arkose', 'clas': 'clastic', 'Psool': 'pseudo oolite', 'Strat': 'strata', 'Bdg': 'bedding', 'bri': 'bright', 'drsy': 'drusy', 'tstg': 'testing', 'Scol': 'scolecodonts', 'crpld': 'crumpled', 'SOCM': 'slight oil cut mud', 'rec': 'recovered', 'Fvst': 'favosites*', 'sbrndd': 'sub rounded', 'p.p.': 'pin-poin', 'HO': 'heavy oil', 'olv': 'olive', 'Mdst': 'mudstone', 's & p': 'salt and pepper', 'venn': 'vermillon', 'u': 'upper', 'gvl': 'gravel', 'fos': 'fossiliferous', 'pet': 'petroleumiferous', 'Clclt': 'calcilutite', 'OSR': 'oil source rock', 'Len': 'lens', 'pel': 'pellet', 'circ': 'circulation', 'prom': 'prominently', 'fol': 'foliated', 'peld': 'pelletoidal', 'Tent': 'tentaculites*', 'prob': 'probably', 'bd': 'bed', 'flky': 'flaky', 'bf': 'buff', 'LL8': 'laterolog-8', 'cgl': 'conglomerate', 'Gwke': 'graywacke', 'slky': 'silky', 'Grap': 'graptolite', 'Bor': 'bored', 'bo': 'bophaceous', 'Bot': 'botryoid', 'phen': 'phenocrysts', 'posa': 'possible', 'bu': 'buff', 'sel': 'selenite', 'Gran': 'granule', 'r.f.p': 'rounded frosted pitted', 'Clslt': 'calcisiltite', 'ss': 'sandstone', 'Uc': 'underclay', 'oo': 'ooidal', 'GOR': 'gas-to-oil ratio', 'Clcrd': 'calcirudite', 'euhed': 'euhedral', 'Solen': 'solenopora*', 'Euryamph': 'euryamphipora*', 'Ptg': 

In [122]:
def expand_abbreviations(description):
    return Lexicon.default().expand_abbreviations(description)

In [123]:
df1['DESCRIPTION_FULL'] = df1['DESCRIPTION'].apply(lambda x:expand_abbreviations(x))

C:\Users\peter\AppData\Local\Temp\ipykernel_23788\2420178955.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['DESCRIPTION_FULL'] = df1['DESCRIPTION'].apply(lambda x:expand_abbreviations(x))

In [94]:
df1

,Tot Depth,TVD Depth,ROP ft/hr,WOB,RPM,SPP,TORQUE,FLWpmps,MW IN,MW OUT,...,nC4 main,iC5 main,nC5 main,D Exp,SAND,SHALE,SILTSTONE,CEMENT,DESCRIPTION,DESCRIPTION_FULL
86,7990.0,7990.0,58.5,12.9,80.0,2872.0,4.24,1065.35,9.2,9.2,...,0.0,1.0,1.0,0.86,-999.25,80.0,-999.25,20.0,Cement.,Cement.
87,7991.0,7991.0,94.0,12.7,81.0,2875.0,5.3,1063.39,9.2,9.2,...,0.0,0.0,1.0,0.77,-999.25,80.0,-999.25,20.0,nan,nan
88,7992.0,7992.0,109.5,12.2,81.0,2874.0,4.58,1058.3,9.2,9.2,...,0.0,0.0,0.0,0.62,-999.25,80.0,-999.25,20.0,"Shale: grn, lt gry, sft - frm, stk,","Shale: grn, lighter greyish, soft - frm, stk,"
89,7993.0,7993.0,6.3,10.4,79.0,2877.0,3.57,1059.57,9.2,9.2,...,2.0,7.0,10.0,1.24,-999.25,80.0,-999.25,20.0,"subblky, blky, subfiss-fiss, non calc.","subblky, blocky, subfiss-fiss, non calcitareous."
90,7994.0,7994.0,25.9,7.6,81.0,2839.0,3.12,1052.27,9.2,9.2,...,1.0,4.0,10.0,0.92,-999.25,80.0,-999.25,20.0,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7548,15343.0,15285.3,15.1,11.7,111.0,3922.0,11.18,877.15,11.2,10.6,...,6.0,3.0,2.0,1.01,30.0,70.0,-999.25,-999.25,nan,nan
7555,15350.0,15292.1,15.4,23.6,111.0,3915.0,14.55,877.25,11.2,10.6,...,8.0,4.0,5.0,1.2,30.0,70.0,-999.25,-999.25,nan,nan
7556,15351.0,15293.2,34.5,24.6,111.0,3915.0,13.55,877.37,11.2,10.6,...,8.0,3.0,5.0,1.05,30.0,70.0,-999.25,-999.25,nan,nan
7560,15355.0,15297.1,25.3,23.2,111.0,3911.0,14.32,877.01,11.2,10.6,...,6.0,4.0,4.0,1.1,30.0,70.0,-999.25,-999.25,nan,nan
7591,15385.0,15326.9,13.6,20.6,111.0,3934.0,12.42,877.08,11.2,10.6,...,8.0,5.0,3.0,1.18,30.0,70.0,-999.25,-999.25,nan,nan

In [95]:
df1.to_csv('Shale_full_description.csv', index = False)